funciona de maneira semelhante ao numpy

In [9]:
import torch
x = torch.arange(12).reshape(3,4)
print(f"Tensor x:\n{x}")

col_2 = x[:, 2] # Seleciona a coluna 2
print(f"Coluna 2:\n{col_2}")
row_1 = x[1, :] # Seleciona a linha 1
print(f"Linha 1:\n{row_1}")
coordinates = x[1, 1] # Seleciona a coordenada 1,3
print(f"Coordenada (1,1): {coordinates}")

Tensor x:
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
Coluna 2:
tensor([ 2,  6, 10])
Linha 1:
tensor([4, 5, 6, 7])
Coordenada (1,1): 5


argmax, acha o index do maior valor (é assim que o modelo acha a predição final)

In [15]:
scores = torch.tensor(
    [[10., 20., 30.],
     [5., 100., 15.]])
best_index = torch.argmax(scores, dim=1) # Retorna o índice do maior valor
print(f"Índice das maiores notas de cada linha: {best_index}")

Índice das maiores notas de cada linha: tensor([2, 1])


gather, permite pegar uma lista de indices em cada uma das linhas

In [20]:
indices_to_get = torch.tensor([[0], [2], [3]]) # Índices das linhas que queremos pegar
selected_values = torch.gather(x, dim=1, index=indices_to_get) # seleciona os valores das linahs 0, 1 e 2, nas colunas 0, 2 e 3 respectivamente
print(f"Valores selecionados:\n{selected_values}")

Valores selecionados:
tensor([[ 0],
        [ 6],
        [11]])
