Pattern 1: Criação direta de uma fonte de dados

In [2]:
import torch # importando a biblioteca torch

data = [[1,2,3], [4,5,6]] # input é uma lista comum em python
my_tensor = torch.tensor(data) # transformamos em um tensor chamando a função torch.tensor e passando a lista como parametro

my_tensor # printando o output

tensor([[1, 2, 3],
        [4, 5, 6]])

Pattern 2: Criação direta de um formato requisitado

In [3]:
shape = (2,2) # definindo o formato requisitado

ones = torch.ones(shape) # chamando a função ones (cria um tensor preenchido com 1) com o formato definido
zeros = torch.zeros(shape) # chamando a função zeros (cria um tenso preenchido com 0) com o formato definido
random = torch.rand(shape) # chamando a função rand (cria um tensor preenchido com valores aleatórios) com o formato definido

print(f"Ones:\n{ones}") # printando o tensor preenchido com 1
print(f"Zeros:\n{zeros}") # printando o tensor preenchido com 0
print(f"Random:\n{random}") # printando o tensor preenchido com valores aleatórios


Ones:
tensor([[1., 1.],
        [1., 1.]])
Zeros:
tensor([[0., 0.],
        [0., 0.]])
Random:
tensor([[0.5702, 0.1126],
        [0.4011, 0.9645]])


Pattern 3: Criação por cópia de outro tensor

In [ ]:
template = torch.tensor ([[1,2], [3,4]]) # input 1: template de um tensor
rand_like = torch.rand_like(template, dtype=torch.float) # input 2: chamando a função rand_like (cria um tensor preenchido com valores aleatórios) passando o template como parametro e definindo o tipo de dado como float
# basicamente, cria um novo tensor com as mesmas propriedades do tensor de entrada, podendo realizar mudanças como o tipo de dado por exmplo
print(f"Template:\n{template}") # printando o template
print(f"Random like:\n{rand_like}") # printando o tensor preenchido com valores aleatórios

Template:
tensor([[1, 2],
        [3, 4]])
Random like:
tensor([[0.2230, 0.1676],
        [0.2994, 0.7485]])
